-- Visual settings for standalone views.
-- Reload Actor after changing this file.
return {
    -- Shared appearance for Enemy List, Target Bar and Inventory.
    -- RGBA colors. Reload Actor after editing. Layout sizes remain per-view.
    shared_style = {
        font = 'Arial',
        background = {18, 22, 30, 205},
        outline = {100, 115, 135, 220},
        text = {220, 230, 240, 255},
        muted = {145, 155, 170, 255},
        accent = {130, 210, 255, 255},
        warning = {255, 200, 90, 255},
        danger = {255, 110, 110, 255},
    },
    target_bar = {
        style = 'classic',
        x = 460,
        y = 70,
        width = 360,
        padding = 7,
        clean = false,
        font = 'Arial',

        background_color = {18, 22, 30, 205},
        outline_color = {115, 125, 145, 235},

        title = {
            text = 'TARGET',
            height = 16,
            size = 9,
            color = {225, 235, 245, 255},
        },
        target = {
            height = 20,
            hp_width = 52,
            hp_size = 12,
            hp_color = {255, 235, 235, 255},
            name_size = 12,
            name_color = {255, 245, 235, 255},
            defeated_name_color = {145, 150, 160, 255},
            distance_width = 70,
            distance_size = 8,
            distance_color = {205, 215, 230, 255},
            show_id = false,
        },
        hp_bar = {
            height = 12,
            background_image = 'media/ui/bar.png',
            fill_image = 'media/ui/bar_fill_hp.png',
            fill_margin = {5, 7, 0, 0},
        },
        action = {
            show = true,
            title_offset = 64,
            icon_size = 14,
            gap = 4,
            text_size = 9,
            text_color = {245, 245, 255, 255},
            cast_height = 4,
            cast_background_image = 'media/ui/bar.png',
            cast_fill_image = 'media/ui/bar_fill_mp.png',
            cast_fill_margin = {2, 3, 0, 0},
        },
        skillchain = {
            show = true,
            size = 16,
            gap = 2,
            top_gap = 3,
        },
        effects = {
            show = true,
            show_timers = true,
            max = 20,
            per_row = 10,
            size = 22,
            gap = 3,
            top_gap = 4,
            row_gap = 3,
            timer_height = 10,
            timer_size = 7,
            timer_color = {245, 245, 245, 255},
        },
        styles = {
            classic = {},
            compact = {
                width = 310,
                padding = 5,
                background_color = {12, 16, 24, 175},
                outline_color = {90, 105, 130, 210},
                title = {
                    height = 16,
                    size = 8,
                    color = {190, 205, 225, 255},
                },
                target = {
                    height = 17,
                    hp_width = 44,
                    hp_size = 10,
                    name_size = 10,
                    distance_width = 54,
                    distance_size = 7,
                },
                hp_bar = {
                    height = 9,
                    fill_margin = {4, 6, 0, 0},
                },
                action = {
                    title_offset = 54,
                    icon_size = 10,
                    gap = 3,
                    text_size = 7,
                    cast_height = 2,
                },
                skillchain = {
                    size = 13,
                    gap = 1,
                    top_gap = 2,
                },
                effects = {
                    size = 18,
                    gap = 2,
                    top_gap = 3,
                    row_gap = 2,
                    timer_height = 8,
                    timer_size = 6,
                },
            },
            ff7 = {
                width = 360,
                padding = 9,
                font = 'Trebuchet MS',
                layout = {
                    hp_side = 'right',
                    distance_row = 'title',
                    bar_inset = 22,
                    effects_inset = 22,
                    title_align = 'left',
                },
                background_color = {8, 24, 112, 238},
                outline_color = {235, 240, 255, 255},
                outline_thickness = 2,
                inner_outline_color = {92, 126, 210, 255},
                inner_outline_inset = 4,
                title = {
                    text = 'ENEMY',
                    height = 17,
                    size = 10,
                    color = {205, 220, 255, 255},
                },
                target = {
                    height = 21,
                    hp_width = 54,
                    hp_size = 12,
                    hp_color = {255, 255, 255, 255},
                    name_size = 12,
                    name_color = {255, 255, 255, 255},
                    defeated_name_color = {150, 165, 200, 255},
                    distance_width = 66,
                    distance_size = 8,
                    distance_color = {195, 215, 255, 255},
                },
                hp_bar = {
                    height = 10,
                    fill_margin = {4, 6, 0, 0},
                },
                action = {
                    title_offset = 58,
                    icon_size = 14,
                    text_size = 9,
                    text_color = {255, 255, 255, 255},
                    cast_height = 3,
                },
                skillchain = {
                    size = 16,
                    gap = 2,
                    top_gap = 4,
                },
                effects = {
                    size = 21,
                    gap = 3,
                    top_gap = 5,
                    row_gap = 3,
                    timer_height = 9,
                    timer_size = 7,
                    timer_color = {225, 235, 255, 255},
                },
            },
        },
        settings_window = {
            width = 285,
            height = 202,
            gap = 8,
            background_color = {18, 22, 30, 235},
            outline_color = {115, 125, 145, 255},
        },
    },
}
