--custom addition to buffs

return {
	[1] = {type = 'Debuff',origin = ''},
	[2] = {type = 'Debuff',origin = '',response = {7,1}},
	[3] = {type = 'Debuff',origin = '',response = 14},
	[4] = {type = 'Debuff',origin = '',response = 15},
	[5] = {type = 'Debuff',origin = '',response = 16},
	[6] = {type = 'Debuff',origin = '',response = 17},
	[7] = {type = 'Debuff',origin = '',response = 18},
	[8] = {type = 'Debuff',origin = '',response = 19},
	[9] = {type = 'Debuff',origin = '',response = 20},
	[10] = {type = 'Debuff',origin = ''},
	[11] = {type = 'Debuff',origin = '',response = 143},
	[12] = {type = 'Debuff',origin = '',response = 143},
	[13] = {type = 'Debuff',origin = '',response = 143},
	[14] = {type = 'Debuff',origin = ''},
	[15] = {type = 'Debuff',origin = '',response = 20},
	[16] = {type = 'Debuff',origin = ''},
	[17] = {type = 'Debuff',origin = ''},
	[18] = {type = 'Debuff',origin = ''},
	[19] = {type = 'Debuff',origin = '',response = {7,1}},
	[20] = {type = 'Debuff',origin = '',response = 20},
	[21] = {type = 'Debuff',origin = '',response = 143},
	[22] = {type = 'Debuff',origin = ''},
	[23] = {type = 'Debuff',origin = ''},
	[24] = {type = 'Debuff',origin = ''},
	[25] = {type = 'Debuff',origin = ''},
	[26] = {type = 'Debuff',origin = ''},
	[27] = {type = 'Debuff',origin = ''},
	[28] = {type = 'Debuff',origin = ''},
	[29] = {type = 'Debuff',origin = ''},
	[30] = {type = 'Debuff',origin = ''},
	[31] = {type = 'Debuff',origin = '',response = 19},
	[32] = {type = 'Buff',origin = ''},
	[33] = {type = 'Buff',origin = ''},
	[34] = {type = 'Buff',origin = ''},
	[35] = {type = 'Buff',origin = ''},
	[36] = {type = 'Buff',origin = 'Copy Image'},
	[37] = {type = 'Buff',origin = ''},
	[38] = {type = 'Buff',origin = ''},
	[39] = {type = 'Buff',origin = ''},
	[40] = {type = 'Buff',origin = ''},
	[41] = {type = 'Buff',origin = ''},
	[42] = {type = 'Buff',origin = ''},
	[43] = {type = 'Buff',origin = ''},
	[44] = {type = 'Buff',origin = ''},
	[45] = {type = 'Buff',origin = ''},
	[46] = {type = 'Buff',origin = ''},
	[47] = {type = 'Buff',origin = ''},
	[48] = {type = 'Buff',origin = ''},
	[49] = {type = 'Buff',origin = ''},
	[50] = {type = 'Buff',origin = ''},
	[51] = {type = 'Buff',origin = ''},
	[52] = {type = 'Buff',origin = ''},
	[53] = {type = 'Buff',origin = ''},
	[54] = {type = 'Buff',origin = ''},
	[55] = {type = 'Buff',origin = ''},
	[56] = {type = 'Buff',origin = ''},
	[57] = {type = 'Buff',origin = ''},
	[58] = {type = 'Buff',origin = ''},
	[59] = {type = 'Buff',origin = ''},
	[60] = {type = 'Buff',origin = ''},
	[61] = {type = 'Buff',origin = ''},
	[62] = {type = 'Buff',origin = ''},
	[63] = {type = 'Buff',origin = ''},
	[64] = {type = 'Buff',origin = ''},
	[65] = {type = 'Buff',origin = ''},
	[66] = {type = 'Buff',origin = 'Copy Image'},
	[67] = {type = 'Buff',origin = ''},
	[68] = {type = 'Buff',origin = ''},
	[69] = {type = 'Buff',origin = ''},
	[70] = {type = 'Buff',origin = ''},
	[71] = {type = 'Buff',origin = ''},
	[72] = {type = 'Buff',origin = ''},
	[73] = {type = 'Buff',origin = ''},
	[74] = {type = 'Buff',origin = ''},
	[75] = {type = 'Buff',origin = ''},
	[76] = {type = 'Buff',origin = ''},
	[77] = {type = 'Buff',origin = ''},
	[78] = {type = 'Buff',origin = ''},
	[79] = {type = 'Buff',origin = ''},
	[80] = {type = 'Buff',origin = ''},
	[81] = {type = 'Buff',origin = ''},
	[82] = {type = 'Buff',origin = ''},
	[83] = {type = 'Buff',origin = ''},
	[84] = {type = 'Buff',origin = ''},
	[85] = {type = 'Buff',origin = ''},
	[86] = {type = 'Buff',origin = ''},
	[87] = {type = 'Buff',origin = ''},
	[88] = {type = 'Buff',origin = ''},
	[89] = {type = 'Buff',origin = ''},
	[90] = {type = 'Buff',origin = ''},
	[91] = {type = 'Buff',origin = ''},
	[92] = {type = 'Buff',origin = ''},
	[93] = {type = 'Buff',origin = ''},
	[94] = {type = 'Buff',origin = ''},
	[95] = {type = 'Buff',origin = ''},
	[96] = {type = 'Buff',origin = ''},
	[97] = {type = 'Buff',origin = ''},
	[98] = {type = 'Buff',origin = ''},
	[99] = {type = 'Buff',origin = ''},
	[100] = {type = 'Buff',origin = ''},
	[101] = {type = 'Buff',origin = ''},
	[102] = {type = 'Buff',origin = ''},
	[103] = {type = 'Buff',origin = ''},
	[104] = {type = 'Buff',origin = ''},
	[105] = {type = 'Buff',origin = ''},
	[106] = {type = 'Buff',origin = ''},
	[107] = {type = 'Buff',origin = ''},
	[108] = {type = 'Buff',origin = ''},
	[109] = {type = 'Buff',origin = ''},
	[110] = {type = 'Buff',origin = ''},
	[111] = {type = 'Buff',origin = ''},
	[112] = {type = 'Buff',origin = ''},
	[113] = {type = 'Buff',origin = ''},
	[114] = {type = 'Buff',origin = ''},
	[115] = {type = 'Buff',origin = ''},
	[116] = {type = 'Buff',origin = ''},
	[117] = {type = 'Buff',origin = ''},
	[118] = {type = 'Buff',origin = ''},
	[119] = {type = 'Buff',origin = ''},
	[120] = {type = 'Buff',origin = ''},
	[121] = {type = 'Buff',origin = ''},
	[122] = {type = 'Buff',origin = ''},
	[123] = {type = 'Buff',origin = ''},
	[124] = {type = 'Buff',origin = ''},
	[125] = {type = 'Buff',origin = ''},
	[126] = {type = 'Buff',origin = ''},
	[127] = {type = 'Buff',origin = ''},
	[128] = {type = 'Debuff',origin = '',response = 143},
	[129] = {type = 'Debuff',origin = '',response = 143},
	[130] = {type = 'Debuff',origin = '',response = 143},
	[131] = {type = 'Debuff',origin = '',response = 143},
	[132] = {type = 'Debuff',origin = '',response = 143},
	[133] = {type = 'Debuff',origin = '',response = 143},
	[134] = {type = 'Debuff',origin = '',response = 143},
	[135] = {type = 'Debuff',origin = '',response = 143},
	[136] = {type = 'Debuff',origin = '',response = 143},
	[137] = {type = 'Debuff',origin = '',response = 143},
	[138] = {type = 'Debuff',origin = '',response = 143},
	[139] = {type = 'Debuff',origin = '',response = 143},
	[140] = {type = 'Debuff',origin = '',response = 143},
	[141] = {type = 'Debuff',origin = '',response = 143},
	[142] = {type = 'Debuff',origin = '',response = 143},
	[143] = {type = 'Event_Debuff',origin = ''},
	[144] = {type = 'Debuff',origin = '',response = 143},
	[145] = {type = 'Debuff',origin = '',response = 143},
	[146] = {type = 'Debuff',origin = '',response = 143},
	[147] = {type = 'Debuff',origin = '',response = 143},
	[148] = {type = 'Debuff',origin = '',response = 143},
	[149] = {type = 'Debuff',origin = '',response = 143},
	[150] = {type = 'Buff',origin = ''},
	[151] = {type = 'Buff',origin = ''},
	[152] = {type = 'Buff',origin = ''},
	[153] = {type = 'Buff',origin = ''},
	[154] = {type = 'Buff',origin = ''},
	[155] = {type = 'Debuff',origin = ''},
	[156] = {type = 'Debuff',origin = ''},
	[157] = {type = 'Event_Debuff',origin = ''},
	[158] = {type = 'Debuff',origin = ''},
	[159] = {type = 'Debuff',origin = ''},
	[160] = {type = 'Debuff',origin = ''},
	[161] = {type = 'Buff',origin = ''},
	[162] = {type = 'Buff',origin = ''},
	[163] = {type = 'Buff',origin = ''},
	[164] = {type = 'Buff',origin = ''},
	[165] = {type = 'Buff',origin = ''},
	[166] = {type = 'Buff',origin = ''},
	[167] = {type = 'Debuff',origin = '',response = 143},
	[168] = {type = 'Debuff',origin = ''},
	[169] = {type = 'Buff',origin = ''},
	[170] = {type = 'Buff',origin = ''},
	[171] = {type = 'Buff',origin = ''},
	[172] = {type = 'Buff',origin = ''},
	[173] = {type = 'Buff',origin = ''},
	[174] = {type = 'Debuff',origin = '',response = 143},
	[175] = {type = 'Debuff',origin = '',response = 143},
	[176] = {type = 'Buff',origin = ''},
	[177] = {type = 'Debuff',origin = ''},
	[178] = {type = 'Buff',origin = ''},
	[179] = {type = 'Buff',origin = ''},
	[180] = {type = 'Buff',origin = ''},
	[181] = {type = 'Buff',origin = ''},
	[182] = {type = 'Buff',origin = ''},
	[183] = {type = 'Buff',origin = ''},
	[184] = {type = 'Buff',origin = ''},
	[185] = {type = 'Buff',origin = ''},
	[186] = {type = 'Buff',origin = ''},
	[187] = {type = 'Buff',origin = ''},
	[188] = {type = 'Buff',origin = ''},
	[189] = {type = 'Debuff',origin = '',response = 143},
	[190] = {type = 'Buff',origin = ''},
	[191] = {type = 'Buff',origin = ''},
	[192] = {type = 'Debuff',origin = 'Song',response = 143},
	[193] = {type = 'Debuff',origin = 'Song',response = {7,1}},
	[194] = {type = 'Debuff',origin = 'Song',response = 143},
	[195] = {type = 'Buff',origin = 'Song'},
	[196] = {type = 'Buff',origin = 'Song'},
	[197] = {type = 'Buff',origin = 'Song'},
	[198] = {type = 'Buff',origin = 'Song'},
	[199] = {type = 'Buff',origin = 'Song'},
	[200] = {type = 'Buff',origin = 'Song'},
	[201] = {type = 'Buff',origin = 'Song'},
	[202] = {type = 'Buff',origin = 'Song'},
	[203] = {type = 'Buff',origin = 'Song'},
	[204] = {type = 'Buff',origin = 'Song'},
	[205] = {type = 'Buff',origin = 'Song'},
	[206] = {type = 'Buff',origin = 'Song'},
	[207] = {type = 'Buff',origin = 'Song'},
	[208] = {type = 'Buff',origin = 'Song'},
	[209] = {type = 'Buff',origin = 'Song'},
	[210] = {type = 'Buff',origin = 'Song'},
	[211] = {type = 'Buff',origin = 'Song'},
	[212] = {type = 'Buff',origin = 'Song'},
	[213] = {type = 'Buff',origin = 'Song'},
	[214] = {type = 'Buff',origin = 'Song'},
	[215] = {type = 'Buff',origin = 'Song'},
	[216] = {type = 'Buff',origin = 'Song'},
	[217] = {type = 'Buff',origin = 'Song'},
	[218] = {type = 'Buff',origin = 'Song'},
	[219] = {type = 'Buff',origin = 'Song'},
	[220] = {type = 'Buff',origin = 'Song'},
	[221] = {type = 'Buff',origin = 'Song'},
	[222] = {type = 'Buff',origin = 'Song'},
	[223] = {type = 'Buff',origin = 'Song'},
	[224] = {type = 'Buff',origin = ''},
	[225] = {type = 'Buff',origin = ''},
	[226] = {type = 'Buff',origin = ''},
	[227] = {type = 'Buff',origin = ''},
	[228] = {type = 'Buff',origin = ''},
	[229] = {type = 'Buff',origin = ''},
	[230] = {type = 'Buff',origin = ''},
	[231] = {type = 'Buff',origin = ''},
	[232] = {type = 'Buff',origin = ''},
	[233] = {type = 'Buff',origin = ''},
	[234] = {type = 'Buff',origin = ''},
	[235] = {type = 'Buff',origin = ''},
	[236] = {type = 'Buff',origin = ''},
	[237] = {type = 'Buff',origin = ''},
	[238] = {type = 'Buff',origin = ''},
	[239] = {type = 'Buff',origin = ''},
	[240] = {type = 'Buff',origin = ''},
	[241] = {type = 'Buff',origin = ''},
	[242] = {type = 'Buff',origin = ''},
	[243] = {type = 'Buff',origin = ''},
	[244] = {type = 'Buff',origin = ''},
	[245] = {type = 'Buff',origin = ''},
	[246] = {type = 'Buff',origin = ''},
	[247] = {type = 'Buff',origin = ''},
	[248] = {type = 'Buff',origin = ''},
	[249] = {type = 'Buff',origin = ''},
	[250] = {type = 'Buff',origin = ''},
	[251] = {type = 'Buff',origin = ''},
	[252] = {type = 'Buff',origin = ''},
	[253] = {type = 'Buff',origin = ''},
	[254] = {type = 'Buff',origin = ''},
	[255] = {type = 'Buff',origin = ''},
	[256] = {type = 'Buff',origin = ''},
	[257] = {type = 'Buff',origin = ''},
	[258] = {type = 'Buff',origin = ''},
	[259] = {type = 'Debuff',origin = ''},
	[260] = {type = 'Debuff',origin = ''},
	[261] = {type = 'Debuff',origin = ''},
	[262] = {type = 'Debuff',origin = ''},
	[263] = {type = 'Debuff',origin = ''},
	[264] = {type = 'Debuff',origin = ''},
	[265] = {type = 'Buff',origin = ''},
	[266] = {type = 'Buff',origin = ''},
	[267] = {type = 'Buff',origin = ''},
	[268] = {type = 'Buff',origin = ''},
	[269] = {type = 'Buff',origin = ''},
	[270] = {type = 'Buff',origin = 'After effect'},
	[271] = {type = 'Buff',origin = 'After effect'},
	[272] = {type = 'Buff',origin = 'After effect'},
	[273] = {type = 'Buff',origin = 'After effect'},
	[274] = {type = 'Buff',origin = ''},
	[275] = {type = 'Buff',origin = ''},
	[276] = {type = 'Buff',origin = ''},
	[277] = {type = 'Buff',origin = ''},
	[278] = {type = 'Buff',origin = ''},
	[279] = {type = 'Buff',origin = ''},
	[280] = {type = 'Buff',origin = ''},
	[281] = {type = 'Buff',origin = ''},
	[282] = {type = 'Buff',origin = ''},
	[283] = {type = 'Buff',origin = ''},
	[284] = {type = 'Buff',origin = ''},
	[285] = {type = 'Buff',origin = ''},
	[286] = {type = 'Buff',origin = ''},
	[287] = {type = 'Buff',origin = ''},
	[288] = {type = 'Buff',origin = ''},
	[289] = {type = 'Buff',origin = ''},
	[290] = {type = 'Buff',origin = ''},
	[291] = {type = 'Buff',origin = ''},
	[292] = {type = 'Buff',origin = ''},
	[293] = {type = 'Buff',origin = ''},
	[294] = {type = 'Buff',origin = ''},
	[295] = {type = 'Buff',origin = ''},
	[296] = {type = 'Buff',origin = ''},
	[297] = {type = 'Buff',origin = ''},
	[298] = {type = 'Debuff',origin = '',response = 143},
	[299] = {type = 'Debuff',origin = ''},
	[300] = {type = 'Buff',origin = 'Fire Maneuver'},
	[301] = {type = 'Buff',origin = 'Ice Maneuver'},
	[302] = {type = 'Buff',origin = 'Wind Maneuver'},
	[303] = {type = 'Buff',origin = 'Earth Maneuver'},
	[304] = {type = 'Buff',origin = 'Thunder Maneuver'},
	[305] = {type = 'Buff',origin = 'Water Maneuver'},
	[306] = {type = 'Buff',origin = 'Light Maneuver'},
	[307] = {type = 'Buff',origin = 'Dark Maneuver'},
	[308] = {type = 'Buff',origin = ''},
	[309] = {type = 'Buff',origin = ''},
	[310] = {type = 'Buff',origin = 'CorsairRoll'},
	[311] = {type = 'Buff',origin = 'CorsairRoll'},
	[312] = {type = 'Buff',origin = 'CorsairRoll'},
	[313] = {type = 'Buff',origin = 'CorsairRoll'},
	[314] = {type = 'Buff',origin = 'CorsairRoll'},
	[315] = {type = 'Buff',origin = 'CorsairRoll'},
	[316] = {type = 'Buff',origin = 'CorsairRoll'},
	[317] = {type = 'Buff',origin = 'CorsairRoll'},
	[318] = {type = 'Buff',origin = 'CorsairRoll'},
	[319] = {type = 'Buff',origin = 'CorsairRoll'},
	[320] = {type = 'Buff',origin = 'CorsairRoll'},
	[321] = {type = 'Buff',origin = 'CorsairRoll'},
	[322] = {type = 'Buff',origin = 'CorsairRoll'},
	[323] = {type = 'Buff',origin = 'CorsairRoll'},
	[324] = {type = 'Buff',origin = 'CorsairRoll'},
	[325] = {type = 'Buff',origin = 'CorsairRoll'},
	[326] = {type = 'Buff',origin = 'CorsairRoll'},
	[327] = {type = 'Buff',origin = 'CorsairRoll'},
	[328] = {type = 'Buff',origin = 'CorsairRoll'},
	[329] = {type = 'Buff',origin = 'CorsairRoll'},
	[330] = {type = 'Buff',origin = 'CorsairRoll'},
	[331] = {type = 'Buff',origin = 'CorsairRoll'},
	[332] = {type = 'Buff',origin = 'CorsairRoll'},
	[333] = {type = 'Buff',origin = 'CorsairRoll'},
	[334] = {type = 'Buff',origin = 'CorsairRoll'},
	[335] = {type = 'Buff',origin = 'CorsairRoll'},
	[336] = {type = 'Buff',origin = 'CorsairRoll'},
	[337] = {type = 'Buff',origin = 'CorsairRoll'},
	[338] = {type = 'Buff',origin = 'CorsairRoll'},
	[339] = {type = 'Buff',origin = ''},
	[340] = {type = 'Buff',origin = ''},
	[341] = {type = 'Buff',origin = ''},
	[342] = {type = 'Buff',origin = ''},
	[343] = {type = 'Buff',origin = ''},
	[344] = {type = 'Buff',origin = ''},
	[345] = {type = 'Buff',origin = ''},
	[346] = {type = 'Buff',origin = ''},
	[347] = {type = 'Buff',origin = ''},
	[348] = {type = 'Buff',origin = ''},
	[349] = {type = 'Buff',origin = ''},
	[350] = {type = 'Buff',origin = ''},
	[351] = {type = 'Buff',origin = ''},
	[352] = {type = 'Buff',origin = ''},
	[353] = {type = 'Buff',origin = ''},
	[354] = {type = 'Buff',origin = ''},
	[355] = {type = 'Buff',origin = ''},
	[356] = {type = 'Buff',origin = ''},
	[357] = {type = 'Buff',origin = ''},
	[358] = {type = 'Buff',origin = 'Rune'},
	[359] = {type = 'Buff',origin = 'Rune'},
	[360] = {type = 'Buff',origin = 'Rune'},
	[361] = {type = 'Buff',origin = 'Rune'},
	[362] = {type = 'Buff',origin = 'Rune'},
	[363] = {type = 'Buff',origin = 'Rune'},
	[364] = {type = 'Buff',origin = 'Rune'},
	[365] = {type = 'Buff',origin = ''},
	[366] = {type = 'Buff',origin = ''},
	[367] = {type = 'Buff',origin = ''},
	[368] = {type = 'Buff',origin = ''},
	[369] = {type = 'Buff',origin = ''},
	[370] = {type = 'Buff',origin = ''},
	[371] = {type = 'Buff',origin = ''},
	[372] = {type = 'Buff',origin = ''},
	[373] = {type = 'Buff',origin = ''},
	[374] = {type = 'Buff',origin = ''},
	[375] = {type = 'Buff',origin = ''},
	[376] = {type = 'Buff',origin = ''},
	[377] = {type = 'Buff',origin = ''},
	[378] = {type = 'Buff',origin = ''},
	[379] = {type = 'Buff',origin = ''},
	[380] = {type = 'Buff',origin = ''},
	[381] = {type = 'Buff',origin = ''},
	[382] = {type = 'Buff',origin = ''},
	[383] = {type = 'Buff',origin = ''},
	[384] = {type = 'Buff',origin = ''},
	[385] = {type = 'Buff',origin = ''},
	[386] = {type = 'Debuff',origin = ''},
	[387] = {type = 'Debuff',origin = ''},
	[388] = {type = 'Debuff',origin = ''},
	[389] = {type = 'Debuff',origin = ''},
	[390] = {type = 'Debuff',origin = ''},
	[391] = {type = 'Debuff',origin = ''},
	[392] = {type = 'Debuff',origin = ''},
	[393] = {type = 'Debuff',origin = ''},
	[394] = {type = 'Debuff',origin = ''},
	[395] = {type = 'Debuff',origin = ''},
	[396] = {type = 'Debuff',origin = ''},
	[397] = {type = 'Debuff',origin = ''},
	[398] = {type = 'Debuff',origin = ''},
	[399] = {type = 'Debuff',origin = ''},
	[400] = {type = 'Debuff',origin = ''},
	[401] = {type = 'Buff',origin = ''},
	[402] = {type = 'Buff',origin = ''},
	[403] = {type = 'Buff',origin = ''},
	[404] = {type = 'Buff',origin = ''},
	[405] = {type = 'Buff',origin = ''},
	[406] = {type = 'Buff',origin = ''},
	[407] = {type = 'Buff',origin = ''},
	[408] = {type = 'Buff',origin = ''},
	[409] = {type = 'Buff',origin = ''},
	[410] = {type = 'Buff',origin = ''},
	[411] = {type = 'Buff',origin = ''},
	[412] = {type = 'Buff',origin = ''},
	[413] = {type = 'Buff',origin = ''},
	[414] = {type = 'Buff',origin = ''},
	[415] = {type = 'Buff',origin = ''},
	[416] = {type = 'Buff',origin = ''},
	[417] = {type = 'Buff',origin = ''},
	[418] = {type = 'Buff',origin = ''},
	[419] = {type = 'Buff',origin = ''},
	[420] = {type = 'Buff',origin = ''},
	[421] = {type = 'Buff',origin = ''},
	[422] = {type = 'Buff',origin = ''},
	[423] = {type = 'Buff',origin = ''},
	[424] = {type = 'Buff',origin = ''},
	[425] = {type = 'Buff',origin = ''},
	[426] = {type = 'Buff',origin = ''},
	[427] = {type = 'Buff',origin = ''},
	[428] = {type = 'Buff',origin = ''},
	[429] = {type = 'Buff',origin = ''},
	[430] = {type = 'Buff',origin = ''},
	[431] = {type = 'Buff',origin = ''},
	[432] = {type = 'Buff',origin = ''},
	[433] = {type = 'Buff',origin = ''},
	[434] = {type = 'Buff',origin = ''},
	[435] = {type = 'Buff',origin = ''},
	[436] = {type = 'Buff',origin = ''},
	[437] = {type = 'Buff',origin = ''},
	[438] = {type = 'Buff',origin = ''},
	[439] = {type = 'Buff',origin = ''},
	[440] = {type = 'Buff',origin = ''},
	[441] = {type = 'Buff',origin = ''},
	[442] = {type = 'Buff',origin = ''},
	[443] = {type = 'Buff',origin = ''},
	[444] = {type = 'Buff',origin = 'Copy Image'},
	[445] = {type = 'Buff',origin = 'Copy Image'},
	[446] = {type = 'Buff',origin = 'Copy Image'},
	[447] = {type = 'Buff',origin = ''},
	[448] = {type = 'Debuff',origin = ''},
	[449] = {type = 'Debuff',origin = ''},
	[450] = {type = 'Debuff',origin = ''},
	[451] = {type = 'Debuff',origin = ''},
	[452] = {type = 'Debuff',origin = ''},
	[453] = {type = 'Buff',origin = ''},
	[454] = {type = 'Buff',origin = ''},
	[455] = {type = 'Buff',origin = ''},
	[456] = {type = 'Buff',origin = ''},
	[457] = {type = 'Buff',origin = ''},
	[458] = {type = 'Buff',origin = ''},
	[459] = {type = 'Buff',origin = ''},
	[460] = {type = 'Buff',origin = ''},
	[461] = {type = 'Buff',origin = ''},
	[462] = {type = 'Buff',origin = ''},
	[463] = {type = 'Buff',origin = ''},
	[464] = {type = 'Buff',origin = ''},
	[465] = {type = 'Buff',origin = ''},
	[466] = {type = 'Buff',origin = ''},
	[467] = {type = 'Buff',origin = ''},
	[468] = {type = 'Buff',origin = ''},
	[469] = {type = 'Buff',origin = ''},
	[470] = {type = 'Buff',origin = ''},
	[471] = {type = 'Buff',origin = ''},
	[472] = {type = 'Buff',origin = ''},
	[473] = {type = 'Debuff',origin = ''},
	[474] = {type = 'Buff',origin = ''},
	[475] = {type = 'Buff',origin = ''},
	[476] = {type = 'Buff',origin = ''},
	[477] = {type = 'Buff',origin = ''},
	[478] = {type = 'Buff',origin = ''},
	[479] = {type = 'Buff',origin = ''},
	[480] = {type = 'Buff',origin = ''},
	[481] = {type = 'Buff',origin = ''},
	[482] = {type = 'Buff',origin = ''},
	[483] = {type = 'Buff',origin = ''},
	[484] = {type = 'Buff',origin = ''},
	[485] = {type = 'Buff',origin = ''},
	[486] = {type = 'Buff',origin = ''},
	[487] = {type = 'Buff',origin = ''},
	[488] = {type = 'Buff',origin = ''},
	[489] = {type = 'Buff',origin = 'After effect'},
	[490] = {type = 'Buff',origin = ''},
	[491] = {type = 'Buff',origin = ''},
	[492] = {type = 'Buff',origin = ''},
	[493] = {type = 'Buff',origin = ''},
	[494] = {type = 'Buff',origin = ''},
	[495] = {type = 'Buff',origin = ''},
	[496] = {type = 'Buff',origin = ''},
	[497] = {type = 'Buff',origin = ''},
	[498] = {type = 'Buff',origin = ''},
	[499] = {type = 'Buff',origin = ''},
	[500] = {type = 'Buff',origin = ''},
	[501] = {type = 'Buff',origin = ''},
	[502] = {type = 'Buff',origin = ''},
	[503] = {type = 'Buff',origin = ''},
	[504] = {type = 'Buff',origin = ''},
	[505] = {type = 'Buff',origin = ''},
	[506] = {type = 'Buff',origin = ''},
	[507] = {type = 'Buff',origin = ''},
	[508] = {type = 'Buff',origin = ''},
	[509] = {type = 'Buff',origin = ''},
	[510] = {type = 'Buff',origin = ''},
	[511] = {type = 'Buff',origin = ''},
	[512] = {type = 'Buff',origin = ''},
	[513] = {type = 'Buff',origin = ''},
	[514] = {type = 'Buff',origin = ''},
	[515] = {type = 'Buff',origin = ''},
	[516] = {type = 'Buff',origin = ''},
	[517] = {type = 'Buff',origin = ''},
	[518] = {type = 'Buff',origin = ''},
	[519] = {type = 'Buff',origin = ''},
	[520] = {type = 'Buff',origin = ''},
	[521] = {type = 'Buff',origin = ''},
	[522] = {type = 'Buff',origin = ''},
	[523] = {type = 'Buff',origin = 'Rune'},
	[524] = {type = 'Buff',origin = 'Rune'},
	[525] = {type = 'Buff',origin = 'Rune'},
	[526] = {type = 'Buff',origin = 'Rune'},
	[527] = {type = 'Buff',origin = 'Rune'},
	[528] = {type = 'Buff',origin = 'Rune'},
	[529] = {type = 'Buff',origin = 'Rune'},
	[530] = {type = 'Buff',origin = 'Rune'},
	[531] = {type = 'Buff',origin = ''},
	[532] = {type = 'Buff',origin = ''},
	[533] = {type = 'Buff',origin = ''},
	[534] = {type = 'Buff',origin = ''},
	[535] = {type = 'Buff',origin = ''},
	[536] = {type = 'Buff',origin = ''},
	[537] = {type = 'Buff',origin = ''},
	[538] = {type = 'Buff',origin = ''},
	[539] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[540] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[541] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[542] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[543] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[544] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[545] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[546] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[547] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[548] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[549] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[550] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[551] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[552] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[553] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[554] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[555] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[556] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[557] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[558] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[559] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[560] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[561] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[562] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[563] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[564] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[565] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[566] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[567] = {type = 'Debuff',is_aura = true,origin = 'Geomancy'},
	[568] = {type = 'Buff',origin = ''},
	[569] = {type = 'Buff',origin = ''},
	[570] = {type = 'Buff',origin = ''},
	[571] = {type = 'Buff',origin = ''},
	[572] = {type = 'Debuff',origin = ''},
	[573] = {type = 'Buff',origin = ''},
	[574] = {type = 'Buff',origin = ''},
	[575] = {type = 'Buff',origin = ''},
	[576] = {type = 'Debuff',origin = ''},
	[577] = {type = 'Buff',origin = ''},
	[578] = {type = 'Buff',origin = ''},
	[580] = {type = 'Buff',is_aura = true,origin = 'Geomancy'},
	[581] = {type = 'Buff',origin = ''},
	[582] = {type = 'Buff',origin = ''},
	[583] = {type = 'Buff',origin = ''},
	[584] = {type = 'Buff',origin = ''},
	[586] = {type = 'Buff',origin = ''},
	[589] = {type = 'Buff',origin = ''},
	[590] = {type = 'Buff',origin = ''},
	[591] = {type = 'Buff',origin = ''},
	[592] = {type = 'Buff',origin = ''},
	[593] = {type = 'Buff',origin = ''},
	[594] = {type = 'Buff',origin = ''},
	[595] = {type = 'Buff',origin = ''},
	[596] = {type = 'Buff',origin = ''},
	[598] = {type = 'Buff',origin = ''},
	[601] = {type = 'Buff',origin = ''},
	[612] = {type = 'Buff',origin = ''},
	[615] = {type = 'Buff',origin = ''},
	[621] = {type = 'Buff',origin = ''},
	[628] = {type = 'Buff',origin = ''},
    [798] = {type = 'Debuff',origin = ''},
	[1001] = {type = 'Debuff',origin = ''},
	[1002] = {type = 'Debuff',origin = ''},
    [1101] = {type = 'Debuff',origin = ''},
    [1102] = {type = 'Debuff',origin = ''},
    [1103] = {type = 'Debuff',origin = ''},
    [1104] = {type = 'Debuff',origin = ''},
    [1105] = {type = 'Debuff',origin = ''},
    [1106] = {type = 'Debuff',origin = ''},
    [1107] = {type = 'Debuff',origin = ''},
    [1108] = {type = 'Debuff',origin = ''},
}
